### ISSUE TITLE
Unable save changes in menu editor in Gantry on Grav

### ISSUE THREAD

**Issue by g00ntar** [gantry/gantry5#2323]
I don't know it's related to newest update - it was working few weeks ago - but after I press save button in menu editor I recive Server Error (code 500 in dev tools): `0 - Found duplicate page: 'user/pages/02.dlaczego-bau-plan' vs 'user/pages/01.home'. Please rename or delete one of these folders from your filesystem` but obviously it's not true becouse those are diffrent pages.

----
HERE is error from grav.log
```
[2018-07-05 20:55:13] grav.CRITICAL: Found duplicate page: 'user/pages/02.dlaczego-bau-plan' vs 'user/pages/01.home'.
Please rename or delete one of these folders from your filesystem - 
Trace: 
#0 [internal function]: Gantry\Admin\EventListener->onMenusSave(Object(RocketTheme\Toolbox\Event\Event), 'admin.menus.sav...', Object(RocketTheme\Toolbox\Event\EventDispatcher))
#1 /home/ubuntu/workspace/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'admin.menus.sav...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) 
#2 /home/ubuntu/workspace/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'admin.menus.sav...', Object(RocketTheme\Toolbox\Event\Event)) 
#3 /home/ubuntu/workspace/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('admin.menus.sav...', Object(RocketTheme\Toolbox\Event\Event)) 
#4 /home/ubuntu/workspace/user/plugins/gantry5/src/classes/Gantry/Framework/Base/Gantry.php(155): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('admin.menus.sav...', Object(RocketTheme\Toolbox\Event\Event)) 
#5 /home/ubuntu/workspace/user/plugins/gantry5/src/classes/Gantry/Admin/Controller/Html/Menu.php(167): Gantry\Framework\Base\Gantry->fireEvent('admin.menus.sav...', Object(RocketTheme\Toolbox\Event\Event)) 
#6 [internal function]: Gantry\Admin\Controller\Html\Menu->save('mainmenu') 
#7 /home/ubuntu/workspace/user/plugins/gantry5/src/classes/Gantry/Component/Controller/BaseController.php(91): call_user_func_array(Array, Array) 
#8 /home/ubuntu/workspace/user/plugins/gantry5/src/classes/Gantry/Component/Controller/HtmlController.php(32): Gantry\Component\Controller\BaseController->execute('POST', Array, Array) 
#9 /home/ubuntu/workspace/user/plugins/gantry5/src/classes/Gantry/Admin/Controller/Html/Menu.php(80): Gantry\Component\Controller\HtmlController->execute('POST', Array, Array) 
#10 /home/ubuntu/workspace/user/plugins/gantry5/src/classes/Gantry/Component/Router/Router.php(92): Gantry\Admin\Controller\Html\Menu->execute('POST', Array, Array) 
#11 /home/ubuntu/workspace/user/plugins/gantry5/src/classes/Gantry/Component/Router/Router.php(81): Gantry\Component\Router\Router->execute('menu', 'POST', Array, Array, 'html') 
#12 /home/ubuntu/workspace/user/plugins/gantry5/src/classes/Gantry/Component/Router/Router.php(53): Gantry\Component\Router\Router->execute('menu', 'POST', Array, Array, 'json') 
#13 /home/ubuntu/workspace/user/plugins/gantry5/gantry5.php(332): Gantry\Component\Router\Router->dispatch() 
#14 [internal function]: Grav\Plugin\Gantry5Plugin->onAdminPagesInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) 
#15 /home/ubuntu/workspace/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) 
#16 /home/ubuntu/workspace/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) 
#17 /home/ubuntu/workspace/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) 
#18 /home/ubuntu/workspace/system/src/Grav/Common/Grav.php(283): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) 
#19 /home/ubuntu/workspace/system/src/Grav/Common/Processors/PagesProcessor.php(25): Grav\Common\Grav->fireEvent('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) 
#20 /home/ubuntu/workspace/system/src/Grav/Common/Grav.php(132): Grav\Common\Processors\PagesProcessor->process() 
#21 /home/ubuntu/workspace/system/src/Grav/Common/Grav.php(374): Grav\Common\Grav->Grav\Common\{closure}() 
#22 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('pages', 'Pages', Object(Closure)) 
#23 /home/ubuntu/workspace/system/src/Grav/Common/Grav.php(350): call_user_func_array(Object(Closure), Array) 
#24 /home/ubuntu/workspace/system/src/Grav/Common/Grav.php(133): Grav\Common\Grav->__call('measureTime', Array) 
#25 /home/ubuntu/workspace/index.php(52): Grav\Common\Grav->process() 
#26 {main} [] []
```

Thanks for your effort

**Comment by mahagr** [comment]
Can you send the header yaml (or frontmatter) from both of the pages?

**Comment by g00ntar** [comment]
So... I have setted slug to home for all my pages
```
---
title: Page-title
slug: home
---
```
becouse I want to use it to navigate with this on one page site (using hash anchors).
When I remove slug from front matter everything works fine.

**Comment by mahagr** [comment]
@g00ntar You cannot have 2 slugs named identically in the same path, it will break some of the logic in Grav as the slug is used to name the pages and it doesn't know which one to use.

CC @rhukster

**Comment by mahagr** [comment]
Actually let me test this out in Gantry 5.5 which has menu manager fixes.

**Comment by mahagr** [comment]
The issue still exists. We may want to add a better error message for this.
