### ISSUE TITLE
Error: Unclosed comment

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#2728]
I've got a very strange problem with my Gantry 5 website. Recently whenever I turn on Debug on Joomla's Global Configuration, the website will show a blank page with only 1 line of text:
![image](https://user-images.githubusercontent.com/12814040/99754438-61e8e700-2ab6-11eb-963e-1d17283c9e92.png)
However, the system error log didn't record this error. So I spent a lot of effort trying to find out what could be causing this issue. Now I think it might be related with (not necessary caused by)  Gantry, the reason is as follows:

I have changed the menu item into a simple joomla article page and made sure there is no other components or modules on this page. Now if I change the template to protostar, the page loads without problem, but when I change it back to a gantry template, the error message shows again. I went to system debug plugin and change logging style to "logging almost everything", the logs are as follows:

> 2020-11-20T03:22:43+00:00	CRITICAL 50.116.60.75	error	Uncaught \Throwable of type Twig\Error\SyntaxError thrown. Stack trace: #0 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Lexer.php(276): Twig\Lexer->lexComment()
> #1 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Lexer.php(203): Twig\Lexer->lexData()
> #2 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Environment.php(696): Twig\Lexer->tokenize(Object(Twig\Source))
> #3 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Environment.php(793): Twig\Environment->tokenize(Object(Twig\Source))
> #4 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Environment.php(482): Twig\Environment->compileSource(Object(Twig\Source))
> #5 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Environment.php(445): Twig\Environment->loadClass('__TwigTemplate_...', '@particles/posi...', NULL)
> #6 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Environment.php(611): Twig\Environment->loadTemplate('@particles/posi...')
> #7 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Template.php(361): Twig\Environment->resolveTemplate(Array)
> #8 /home/cchc/public_html/cache/gantry5/it_paradise/twig/9e/9ebd93d053bd7047b4b010244321a9f39d8fd000d354209e67c51fd5deb02865.php(53): Twig\Template->loadTemplate(Array, '@nucleus/conten...', 9)
> #9 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Template.php(455): __TwigTemplate_8b4088083802512c177f574e88c0a4e711563009a6b648a7f0923c370106c77f->doDisplay(Array, Array)
> #10 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
> #11 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array)
> #12 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/TemplateWrapper.php(47): Twig\Template->render(Array, Array)
> #13 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Environment.php(384): Twig\TemplateWrapper->render(Array)
> #14 /home/cchc/public_html/libraries/gantry5/classes/Gantry/Component/Theme/AbstractTheme.php(163): Twig\Environment->render('@nucleus/conten...', Array)
> #15 /home/cchc/public_html/libraries/gantry5/classes/Gantry/Component/Theme/ThemeTrait.php(769): Gantry\Component\Theme\AbstractTheme->render('@nucleus/conten...', Array)
> #16 /home/cchc/public_html/libraries/gantry5/classes/Gantry/Component/Theme/ThemeTrait.php(668): Gantry\Framework\Theme->getContent(Object(stdClass), Array)
> #17 /home/cchc/public_html/libraries/gantry5/classes/Gantry/Component/Theme/ThemeTrait.php(595): Gantry\Framework\Theme->renderContent(Object(stdClass), Array)
> #18 /home/cchc/public_html/libraries/gantry5/classes/Gantry/Component/Theme/ThemeTrait.php(581): Gantry\Framework\Theme->prepareLayout(Array, 0, 0)
> #19 /home/cchc/public_html/libraries/gantry5/classes/Gantry/Component/Theme/ThemeTrait.php(581): Gantry\Framework\Theme->prepareLayout(Array, 0, 0)
> #20 /home/cchc/public_html/libraries/gantry5/classes/Gantry/Component/Theme/ThemeTrait.php(581): Gantry\Framework\Theme->prepareLayout(Array, 0, 0)
> #21 /home/cchc/public_html/libraries/gantry5/classes/Gantry/Component/Theme/ThemeTrait.php(581): Gantry\Framework\Theme->prepareLayout(Array, 0, false)
> #22 /home/cchc/public_html/libraries/gantry5/classes/Gantry/Component/Theme/ThemeTrait.php(424): Gantry\Framework\Theme->prepareLayout(Array)
> #23 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Template.php(702): Gantry\Framework\Theme->segments()
> #24 /home/cchc/public_html/cache/gantry5/it_paradise/twig/fd/fd95727fb1fd39d2f3a794af95fcefd4942da54404e2d241ccb259d839c2f226.php(47): Twig\Template->getAttribute(Object(GantryTheme), 'segments', Array, 'method')
> #25 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Template.php(455): __TwigTemplate_fcf6b84d99ee0c649bbd3565c54e357a0b8455743ec1bdfa54be543f1fe55e65->doDisplay(Array, Array)
> #26 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
> #27 /home/cchc/public_html/cache/gantry5/it_paradise/twig/8f/8f597fd1ad3f08add396204f33328d8bc89707d7b1b4e13ef4f880135c13e855.php(35): Twig\Template->display(Array, Array)
> #28 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Template.php(455): __TwigTemplate_049bc175fb6b7bac2cab934343319fcd6a77e54455f720d9fac0f2bf28551b2f->doDisplay(Array, Array)
> #29 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
> #30 /home/cchc/public_html/cache/gantry5/it_paradise/twig/52/527c846b3d6135bd4dfebd10ba3cb4abe407c2f3512b8517e78dfe03a6ed7e00.php(35): Twig\Template->display(Array, Array)
> #31 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Template.php(455): __TwigTemplate_6e7faa0ae24a7596fbfce0dc7880e4ceb6b1e7a93b86375938b1bc41b68404df->doDisplay(Array, Array)
> #32 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
> #33 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array)
> #34 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/TemplateWrapper.php(47): Twig\Template->render(Array, Array)
> #35 /home/cchc/public_html/libraries/gantry5/vendor/twig/twig/src/Environment.php(384): Twig\TemplateWrapper->render(Array)
> #36 /home/cchc/public_html/libraries/gantry5/classes/Gantry/Component/Theme/AbstractTheme.php(163): Twig\Environment->render('index.html.twig', Array)
> #37 /home/cchc/public_html/templates/it_paradise/index.php(28): Gantry\Component\Theme\AbstractTheme->render('index.html.twig', Array)
> #38 /home/cchc/public_html/libraries/src/Document/HtmlDocument.php(668): require('/home/cchc/publ...')
> #39 /home/cchc/public_html/libraries/src/Document/HtmlDocument.php(730): Joomla\CMS\Document\HtmlDocument->_loadTemplate('/home/cchc/publ...', 'index.php')
> #40 /home/cchc/public_html/libraries/src/Document/HtmlDocument.php(545): Joomla\CMS\Document\HtmlDocument->_fetchTemplate(Array)
> #41 /home/cchc/public_html/libraries/src/Application/CMSApplication.php(1030): Joomla\CMS\Document\HtmlDocument->parse(Array)
> #42 /home/cchc/public_html/libraries/src/Application/SiteApplication.php(778): Joomla\CMS\Application\CMSApplication->render()
> #43 /home/cchc/public_html/libraries/src/Application/CMSApplication.php(202): Joomla\CMS\Application\SiteApplication->render()
> #44 /home/cchc/public_html/index.php(49): Joomla\CMS\Application\CMSApplication->execute()
> #45 {main}
> 

To understand this log is totally beyond my knowledge. So could you please take a quick look and maybe you can give me a hint about where this problem stems from. Thanks in advance.

**Comment by newjie** [comment]
OK. I found the problem. In some twig file that I modified I put `#` at the beginning only of a line only. I put it at the end of the line as well and this problem is no more.
