### ISSUE TITLE
Error: During inheritance of Countable: Uncaught Whoops\Exception\ErrorException: Return type of Twig\Node\Node::count() should either be compatible with Countable::count()

### ISSUE THREAD

**Issue by csbalazs** [gantry/gantry5#3088]
1. I installed clean Joomla 4.2.3 under Wampserver (3.2.9), PHP 8.1.11
2. I installed latest CI build (Gantry 5.5.16-dev-8885f9f4e) and Helium template (5.5.16-dev-8885f9f4e)
3. I set default template to Helium, and got the following error:

Error: During inheritance of Countable: Uncaught Whoops\Exception\ErrorException: Return type of Twig\Node\Node::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\wamp64\www\joomla4\libraries\gantry5\compat\vendor\twig\twig\src\Node\Node.php:213 Stack trace: #0 C:\wamp64\www\joomla4\libraries\gantry5\src\classes\Gantry\Component\Whoops\SystemFacade.php(119): Whoops\Run->handleError(8192, 'Return type of ...', 'C:\\wamp64\\www\\j...', 213) #1 C:\wamp64\www\joomla4\libraries\gantry5\compat\vendor\twig\twig\src\Node\Node.php(23): Gantry\Component\Whoops\SystemFacade->handleError(8192, 'Return type of ...', 'C:\\wamp64\\www\\j...', 213) #2 C:\wamp64\www\joomla4\libraries\vendor\composer\ClassLoader.php(571): include('C:\\wamp64\\www\\j...') #3

Helium template works under PHP version 8.0.13.

![image](https://user-images.githubusercontent.com/1657924/196408469-5e0e0bb9-5e25-4fba-ac40-e6656f1246ca.png)

**Comment by bascherz** [comment]
I am getting this same error with two sites, one each running Hydrogen 5.5.14 and Helium 5.5.14 on Joomla! 4.2.5. I have one other site running the same version of Helium 5.5.15 that does NOT do this.

**Comment by bascherz** [comment]
After upgrading to Gantry 5.5.15 on all my sites, I can no longer use the administrator menu layout manager. That's kind of a big deal, though nowhere nearly as bad as the front end fatal errors. I get this error for every menu on all of my sites using Gantry 5.5.15.

![image](https://user-images.githubusercontent.com/16126098/208312650-229b3086-7854-4b76-802f-33fb677675b1.png)

**Comment by N8Solutions** [comment]
@bascherz since this is a new problem, please open a different issue for this so it can be properly tracked.

**Comment by bascherz** [comment]
It seems the issue has been reported elsewhere (https://github.com/gantry/gantry5/issues/3073), but similar to my posting is intermixed with other issues and this part seems to be getting overlooked/ignored.

I am happy to create a new issue for it, though.

**Comment by N8Solutions** [comment]
I would just comment on the other one rather than open a new issue.

**Comment by bascherz** [comment]
Already created a new issue. https://github.com/gantry/gantry5/issues/3103

**Comment by csbalazs** [comment]
I checked the source code and the Twig version (v1) used by Gantry is no longer supported under PHP 8.1.
Temporary solution, download version v2 of Twig and replace version v1:
1. Go to https://github.com/twigphp/Twig/tree/2.x
2. Click the (green) Code button, then the Download ZIP link
3. Go to \libraries\gantry5\compat\vendor\twig\twig and rename or delete the last twig folder
4. Extract the contents of the downloaded ZIP file to the \libraries\gantry5\compat\vendor\twig\twig folder
After that, the page will also work under the Error Reporting of Joomla!: System Default setting

**Comment by galvani66** [comment]
The solution suggested by csbalazs solved the problem for me.
Bei mir hat der Lösungsvorschlag von csbalazs das Problem gelöst.
